### PR TITLE
added support for external libraries

### PR DESCRIPTION
**Pull request by mtsyganov**
for example to compile firmware with adafruit motor shield drivers

### CODE REVIEW

**Comment by TomFreudenberg** [comment]
Hi Michael ( @mtsyganov )

thanks for your pull request. I am not sure why you have added such a feature. If I understand correct you are searching recursive for LIBS inside added INC pathes. I would not prefer to do such a "magic" because you can add the libs directly via the INC option. 

Lets assume following structure

```
+ arduino
  + libraries
    + servo
      Servo.h

+ myproj
  MySketch.ino
  + includes
  + libraries
    + motor
      Motor.h
```

then you can run compile and build like

``` bash
udoo-arduino-build --flash-sam -L Servo.cpp -I include -I libraries/motor MySketch.ino
```

isn't this easy and clear?

**Comment by TomFreudenberg** [comment]
By the way, I am very happy that someone like and use the udoo-arduino-cli feature. Thanks.

**Comment by mtsyganov** [comment]
Hi Tom,

I need this feature to build my arduino firmware with adafruit motorshield library.
The motorshield library is located in the myproj/libraries/adafruit_motorshield/ directory. So I can include this directory with -I option.
But if I try to compile the project with -L Adafruit_MotorShield.cpp -L Adafruit_PWMServoDriver.cpp options, I get an error, because these files could not be found in the arduino stadard library path. These files are located in the myproj/libraries/adafruit_motorshield directory. 
With my change I can do such compilation.

**Comment by mtsyganov** [comment]
BTW ich komme aus Köln ;) viele Grüße nach Hamburg und frohe Ostern! :)

**Comment by TomFreudenberg** [comment]
Hi Michael, Ostergrüße zurück nach Köln (nahe meiner ursprünglichen Heimat Ddorf)

---

I am guessing you include the motorshield components via

```
#include "adafruit_motorshield.h"
#include "adafruit_pwmservodriver.h"
...
```

Could you please try to compile via

```
udoo-arduino-build --flash-sam -I libraries/adafruit_motorshield YourProject.ino
```

if that should not work just try to add the `cpp` files as additional project files like

```
udoo-arduino-build --flash-sam -I libraries/adafruit_motorshield YourProject.ino libraries/adafruit_motorshield/*.cpp
```

Thanks for reply.

**Comment by mtsyganov** [comment]
both don't work

**Comment by TomFreudenberg** [comment]
hmmm ... may you upload your project or some demo files and structure that I could check what's happen?

**Comment by mtsyganov** [comment]
I have checked out your current repository changeset in the project directory

this is the main project source file testmotorshield.ino

```
#include <Wire.h>
#include "Adafruit_MotorShield.h"
#include "utility/Adafruit_PWMServoDriver.h"

Adafruit_MotorShield AFMS = Adafruit_MotorShield();

void setup() {
  AFMS.begin();
}

void loop() {
  delay(1000);
}
```

this command I run to build the project

```
udoo-arduino-cli/usr/local/lib/udoo-arduino-cli/tools/udoo-arduino-build -A udoo-arduino-cli/usr/local/lib/udoo-arduino-cli -I libraries/adafruit_motorshield -I libraries/adafruit_motorshield/utility -L Wire.cpp -o build --fast testmotorshield.ino
```

the output is

```
testmotorshield.ino:8: warning: undefined reference to `Adafruit_MotorShield::begin(unsigned short)'
```

**Comment by TomFreudenberg** [comment]
Michael, do you please have a download link to the Adafruit library for me?

**Comment by mtsyganov** [comment]
https://learn.adafruit.com/adafruit-motor-shield-v2-for-arduino/install-software

**Comment by TomFreudenberg** [comment]
Hi Michael, I checked it and got it running with standard procedure. 

Assume that Adafruit is located at `<projdir>/libraries/adafruit_motorshield` you have to call

```
udoo-arduino-build -L Wire.cpp -I libraries/adafruit_motorshield -I libraries/adafruit_motorshield/utility testmotorshield.ino libraries/adafruit_motorshield/Adafruit_MotorShield.cpp libraries/adafruit_motorshield/utility/Adafruit_PWMServoDriver.cpp
```

Above looks a bit complicated.

I would prefer to re-arrange the project structure in such a case:

```
+ myproj
   testmotorshield.ino
  + adafruit_motorshield
     Adafruit_Motorshield.cpp
     Adafruit_Motorshield.h
     Adafruit_PWMServoDriver.cpp
     Adafruit_PWMServoDriver.h
```

then the compile would be:

```
udoo-arduino-build -o build -L Wire.cpp -I adafruit_motorshield testmotorshield.ino adafruit_motorshield/*.cpp
```

Attention, you have to change reference of `utility/Adafruit_PWMServoDriver.h` just to `Adafruit_PWMServoDriver.h` in `testmotorshield.ino` and `Adafruit_MotorShield.h`.

**Comment by TomFreudenberg** [comment]
I am thinking about some easier command interface but I do not like the idea to mix INClude and LIBS magic. So, what do you think for an optional relative / local search like

```
udoo-arduino-build -L Wire.cpp -L libraries/adafruit_motorshield/Adafruit_Motorshield.cpp -L libraries/adafruit_motorshield/Adafruit_PWMServoDriver.cpp testmotorshield.ino
```

That sounds consequent to me.

Thanks for your feedback.

**Comment by TomFreudenberg** [comment]
Hi Michael, thanks for input. Hopefully you will agree with the new improvement.

Cheers, Tom

**Comment by mtsyganov** [comment]
sure Tom. Thank you!

**Pull request closed without merging**
